apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: laravel-adminpanel
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8.0 # Safer to use a specific version rather than latest in prod
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            # readOnlyRootFilesystem: true # MySQL often requires complex mounts to run fully readOnly
      volumes:
        - name: mysql-data
          hostPath:
            path: /var/abacus-projects/laravel-adminpanel/mysql-data
            type: DirectoryOrCreate
