apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: laravel-adminpanel
spec:
  selector:
    app: mysql
  clusterIP: None
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306