apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-adminpanel
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
    - port: 80
      name: laravel-port
      targetPort: 80
      nodePort: 30000